# Generated by Django 4.1.9 on 2023-06-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorInferencia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
