# Generated by Django 4.1.9 on 2023-06-03 15:22

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('motorInferencia', '0002_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=150)),
                ('dispositivo_creacion', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=150)),
                ('dispositivo_modificacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('action', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=150)),
                ('dispositivo_creacion', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=150)),
                ('dispositivo_modificacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='KeyWors',
        ),
    ]
