# Generated by Django 4.1.9 on 2023-06-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorInferencia', '0002_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=150)),
                ('dispositivo_creacion', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=150)),
                ('dispositivo_modificacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=500, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=150)),
                ('dispositivo_creacion', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=150)),
                ('dispositivo_modificacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='KeyWors',
        ),
        migrations.AddField(
            model_name='keywordsmodel',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorInferencia.rulemodel'),
        ),
    ]
