# Generated by Django 4.1.9 on 2023-06-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorInferencia', '0003_keywordsmodel_rulemodel_delete_keywors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulemodel',
            name='rule',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
