# Generated by Django 4.1.9 on 2023-06-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorInferencia', '0003_action_keywords_delete_keywors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='Rule',
        ),
    ]
