# Generated by Django 4.1.9 on 2023-06-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorInferencia', '0004_rename_action_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=150)),
                ('dispositivo_creacion', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=150)),
                ('dispositivo_modificacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.RenameField(
            model_name='keywords',
            old_name='action',
            new_name='rule',
        ),
    ]
