# Generated by Django 4.1.9 on 2023-06-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorInferencia', '0004_alter_rulemodel_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulemodel',
            name='rule',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
