# Generated by Django 4.1.9 on 2023-06-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorInferencia', '0005_alter_rulemodel_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsmodel',
            name='keyword',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
